### PR TITLE
Constraints on Preservation Action

### PR DESCRIPTION
**Pull request by mjaddis**
I elaborated preservation_action.json to allow us to say under what conditions a preservation action can be run, e.g. 'mediainfo' can be run for AV property extraction, but only if the input file is in a video file format.    The constraints we need to express are typically ones on the inputs to a preservation action, e.g. mediainfo has an input file and this file must have the property of being a video file, i.e. it must have file format = fmt/199, x-fmt/384 etc.   

There may be other constraints that we need to express other than file format restrictions, so I went for the approach of being able to say 'input item X should have Property Y'.    I also used an 'AnyOf' and 'AllOf' approach so we can say 'item X needs to match any of the properties in a list', e.g. a list of file formats, or that 'item X needs to have every property in a list', e.g. a given height, width and codec.   

In the case of file formats, there are two ways of expressing a constraint that an action can only be used for a set of file format IDs.  One approach recognises that file format is itself a parProperty and hence can be expressed as a constraint that way, the other approach recognises that file format is an entity in its own right and hence a constraint can be expressed as 'input item X should have Format Z'.    The mediaInfo2.json example shows both approaches to help make this clearer.  

We probably need to discuss the best approach to constraints so this PR is more of a 'straw man' to seed discussion than a statement of how it should be done.

### CODE REVIEW

**Comment by ross-spencer** [comment]
@mjaddis how would the PAR handle a new file format? or a format that isn't [identified correctly](https://twitter.com/YvonneTunnat/status/1022108961871474688) by one of the PRONOM based tools? Could the constraints on a preservation action be disabled to allow users to use any action on any file, and rely on the tool's output as guidance?

**Comment by mjaddis** [comment]
@ross-spencer - good question!  At the moment, none of the constraints get enforced in any way.  For example, when executing the mediaInfo2.cwl example it doesn't check the file format of the input file for compliance to any constraints set in the mediainfo2.json PAR definition.  I guess you could consider the constraints in a preservation action as 'advisory' in the sense that they provide examples of where an action is known to work but don't preclude someone from trying to use the action in other scenarios, e.g. for file formats that aren't listed or for new file formats where an action hasn't been tested before.   You might also consider that the job of enforcing the constraints, rigorously or otherwise, is something for a Preservation System to do, e.g.  Archivematica or Preservica.   A preservation action in PAR is providing hints to that system on what to do.   So, in the case of Archivematica's FPR, a mediainfo action in PAR might say that 'characterisation of AV files can be done using MediaInfo and is known to work for formats X,Y,Z and here's a CWL example of how to implement it', which would then need to be mapped to a set Archivematica rules for characterisation and the command to use when those rules fire.  This mapping may or may not be include all the formats listed in the constraint list or could include others after further testing.   Finally, one other approach I had in mind that isn't in the schema yet is to use format families rather than specific pronom IDs, e.g. to say that mediainfo is generally applicable to video formats as opposed to documents, email, images etc.   That would also allow new file formats to be covered by the preservation action without listing them all out explicitly and having to revise the preservation action definition every time a new video format comes out.

**Comment by jackdos** [comment]
We introduced the idea of a format family in the business rule and it was for this reason. If a new format is added to PRONOM, and someone decides, "That's a video format", you add the format to your "Video" family, and as long as you describe all your business rules and actions in terms of the family, it automatically starts applying to the new format. Of course, there are certain scenarios where you might not want that, or where you want to specifically exclude a format. Sticking with Video, you might to say "mediainfo extracts properties from all video files, except format MPEG3000, which causes it to crash horribly", so you might have a constraint that is logically "format is in family Video and format is not MPEG3000".

And by "we introduced", I mean "I stuck something in to represent this idea" rather than "We've elegantly accounted for this". It's definitely a raw v0.01 approach there, so if someone has a good idea for better implementing that idea...

"Incorrectly" identified is an interesting idea. In some sense it's a controversial statement to say "the identification is incorrect and I want to perform this action anyway". In reality, either the signature is incorrect or incomplete, or you are wrong in your assumption about what the file is and the tool is telling you the correct thing. (There's the third "my identification tool is buggy" option, I guess, but that probably amounts to the same as the signature being wrong in terms of how I would go about dealing with it). In the first case, your action should be to correct the signature (or the tool), and re-run identification, at which point, the "problem" disappears. In the second case, your action is to, correctly, not perform the action on that file. Whilst you are deciding which/remediating the issue, I think I would say the file should be treated as somewhat in limbo, and running preservation actions on it is a risky proposition.

But ultimately, Matthew is right, it's the role of the Preservation System to interpret PAR actions and business rules. I don't think that "can you disable constraints in PAR?" is a meaningful question; the question is "can I ignore PAR constraints in my Preservation System". To which the answer should be "you can do whatever you like in your preservation system, in the knowledge that what is described in PAR represents the best information available to the community". Of course, the implementer of the Preservation System has to agree that you can ignore constraints and provide you with that option... :-)

**Comment by ross-spencer** [comment]
> But ultimately, Matthew is right, it's the role of the Preservation System to interpret PAR actions and business rules. I don't think that "can you disable constraints in PAR?" is a meaningful question; the question is "can I ignore PAR constraints in my Preservation System". To which the answer should be "you can do whatever you like in your preservation system, in the knowledge that what is described in PAR represents the best information available to the community". 

Very nice! :+1:

**Pull request merged**
