### PR TITLE
Added business rule schema definition and examples, shortened some pr…

### LINKED ISSUE #10: Add Business Rules schema
We need a schema for the business rules Core entity

### PR DESCRIPTION
**Pull request by jackdos**
…operty names, modified preservation action and format to use a common identifier type.

Closes #10 

I have also pulled the action inputs and outputs into the types schema as I referenced them from the business rules.

I think this speaks to a principle that each schema should be able to reference types if defined internally (i.e. in its own #/definitions), defined in the #/definitions of types, or defined as top level entities in another schema, but not to reference internal types of another schema.

The common parIdentifier type should probably be the id object for each Core entity, defining the id and the namespace in which that id is valid. At the moment I have also included a "prefix" but I think we need to consider how identifiers work in the REST API. Using a common id entity allows us to reference entities within other entities without embedding the entire entity itself (see the business rules example).

### CODE REVIEW

**Comment by mjaddis** [comment]
I tried running br-1.json through ajv (because test_main.py is not runnable on the command line) and it reports:

error: can't resolve reference http://www.parcore.org/schema/types.json/#/definitions/actionOuput from id http://www.parcore.org/schema/business_rule.json/#

Note the typo in actionOuput.

**Comment by jackdos** [comment]
Interesting, it is indeed a typo and presumably shouldn't have validated, but the automated runner has managed to validate it.

**Comment by mjaddis** [comment]
Not sure the automated tests are working properly, I can't get test_main.py to run on the command line with pytest without removing the '.' in front of 'const' on the import statement, but that might be because I'm not familiar with python or pytest.   

For reference, test I did was:

ajv validate \
-s rdss-par/schemas/preservation_action.json \
-r rdss-par/schemas/types.json \
-r rdss-par/schemas/preservation_action_type.json \
-r rdss-par/schemas/par_property.json \
-r rdss-par/schemas/tool.json \
-d rdss-par/examples/md5check.json

**Comment by jackdos** [comment]
Yeah, I agree that I need to make a change. I had them validating with the old test setup this morning, haven't got the pytest one running yet (similarly unfamiliar with the setup). 

I might have lost track somewhere of what changes I'm working with and seem to have left myself in a bit of a merge crisis. This is definitely a tomorrow problem to fix.

**Comment by mjaddis** [comment]
details of how to run test_main are here: https://github.com/JiscRDSS/rdss-par/issues/17

**Comment by mjaddis** [comment]
The definition of preservation action input and preservation action output have been moved to types.json.  Please can they be put back in preservation_action.json.   If the inputs and outputs to an action are in a different schema then it makes it hard to see what's going on - especially as there is more work to come on preservation action to map inputs and outputs to different execution models, e.g. cwl, web services etc.  I understand that moving the definition of input and output was done because they are referenced in some of the business rules, but this can be done equally well by referencing the schemas inside of preservation action.   One way to look at this is (a) whether preservation action inputs and outputs are generic types in the same way as identifiers, families etc. - which I don't think they are - this suggests they don't live in types.json, and (b) whether inputs and outputs are top level entities in the conceptual model in the same way as action, tool, property, business rule - which I don't think they are - this suggests they should remain in preservation_action.json.

**Comment by jackdos** [comment]
@mjaddis I have moved the inputs and outputs back to preservation actions, but have kept some of the name/label shortening. I think everything is now back in a consistent state

**Comment by jackdos** [comment]
also, running "python /usr/lib/python2.7/site-packages/pytest.py -v" from the root of the project is working for me. That's python2.7 on centos7.

**Comment by jhsimpson** [comment]
closes #18

**Pull request merged**
